version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    working_dir: /app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - STORAGE_TYPE=RedisBirthdayStorage
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
    networks:
      - app

  cron_job:
    build: .
    container_name: cron_job
    volumes:
      - ./:/app
    depends_on:
      - redis-server
    networks:
      - app
    entrypoint: sh -c "apt-get update && apt-get -y install cron && cron && tail -f /dev/null"
    command: "0 * * * * /usr/local/bin/python /cron/execute.py"
    restart: always

  redis-server:
    image: redis
    container_name: redis
    networks:
      - app
    ports:
      - "6379:6379"

networks:
  app:
    driver: bridge