version: '3.8'

services:
  webhook:
    build: .
    container_name: webhook
    working_dir: /app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - STORAGE_TYPE=RedisBirthdayStorage
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
    networks:
      - app
    command: "python server/server.py"

  reminder:
    build: .
    container_name: reminder
    working_dir: /app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - STORAGE_TYPE=RedisBirthdayStorage
    volumes:
      - ./:/app
    depends_on:
      - redis-server
    networks:
      - app
    entrypoint: sh -c "apt-get update && apt-get -y install cron && cron && tail -f /dev/null"
    command: "0 * * * * python src/reminders.py"
    restart: always

  redis-server:
    image: redis
    container_name: redis
    networks:
      - app
    ports:
      - "6379:6379"

networks:
  app:
    driver: bridge