service: bots
frameworkVersion: '3'

provider:
  stage: prod
  name: aws
  runtime: python3.11
  region: sa-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource: "arn:aws:s3:::dferencz/birthdays.csv"

functions:
  birthday_reminder:
    handler: src.handlers.remind
    layers:
      - arn:aws:lambda:sa-east-1:378764373381:layer:bots-prod-python-requirements:1
    events:
      - schedule:
          rate: cron(0 3 * * ? *)
  birthday_telegram_api:
    handler: src.handlers.api
    layers:
      - arn:aws:lambda:sa-east-1:378764373381:layer:bots-prod-python-requirements:1
    events:
      - http:
          path: /
          method: post
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    layer: true
    zip: true